# Test bigquery

Upload de catalogue pizeo

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import pandas as pd
from dotenv import load_dotenv
from google.cloud import bigquery

from hydrosense.params import *

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/api_core/_python_version_support.py:273: FutureWarning: You are using a Python version (3.10.6) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)

In [3]:
# 1 Connexion
# 1.1 Charge les variables du fichier .env
load_dotenv(dotenv_path="../.env")


# 1.3. Initialise le client avec la variable définie
client = bigquery.Client(project=GCP_PROJECT_ID)

print(f"Connecté à {GCP_PROJECT_ID} ✅")

Connecté à hydro-sense-498112 ✅

In [4]:
print(os.getenv("GOOGLE_APPLICATION_CREDENTIALS"))
print(GCP_PROJECT_ID)

/home/charourou/projects/Projet_Hydrosense/secrets/hydro-sense-498112-d8b48c4804b5.json
hydro-sense-498112

## 2. TesT du chargement des données

Big Query. requête SQL

In [5]:
# 2 Load test model "piezo_test"
DATASET = BQ_DATASET_ID
TABLE = "chroniques_piezo"
GCP_PROJECT_ID,DATASET,TABLE

('hydro-sense-498112', 'piezometry', 'chroniques_piezo')

In [6]:
from hydrosense.database.bigquery import load_piezo_bq
TARGETS_BSS

['BSS002DEZW',
 'BSS000ZPHJ',
 'BSS000ZQXN',
 'BSS001PGUQ',
 'BSS001QTKG',
 'BSS001QSMT',
 'BSS001QHYH',
 'BSS001QHPU',
 'BSS001RQQE',
 'BSS001SHNE',
 'BSS001VAJT',
 'BSS001UCZQ',
 'BSS001XBKZ',
 'BSS001WVPW',
 'BSS002AFGV',
 'BSS002AXYY',
 'BSS002CAAM',
 'BSS002BGAF',
 'BSS002EDYK']

In [15]:
%%time

for bss in TARGETS_BSS[:]:

    df = load_piezo_bq(bss)
    # query = f"""
    #     SELECT *
    #     FROM `{GCP_PROJECT_ID}.{DATASET}.{TABLE}`
    #     WHERE bss_id = '{bss}'
    #     """
    # try:
    #     query_job = client.query(query)
    #     result = query_job.result()
    #     df = result.to_dataframe()
    print(bss, df['date_mesure'].min(), df['date_mesure'].max(),
              round(df['niveau_nappe_eau'].mean(), 2 )
               )
    # except:
    #     print(bss, "not uploaded from Big Query")
df.head()

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS002DEZW'
        ORDER BY date_mesure

BSS002DEZW : 10755 lignes chargées
BSS002DEZW 1959-01-01 00:00:00 2026-05-30 00:00:00 90.95

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS000ZPHJ'
        ORDER BY date_mesure

BSS000ZPHJ : 7423 lignes chargées
BSS000ZPHJ 2005-12-22 00:00:00 2026-05-29 00:00:00 10.85

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS000ZQXN'
        ORDER BY date_mesure

BSS000ZQXN : 7682 lignes chargées
BSS000ZQXN 2005-02-18 00:00:00 2026-05-29 00:00:00 71.3

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001PGUQ'
        ORDER BY date_mesure

BSS001PGUQ : 13293 lignes chargées
BSS001PGUQ 1989-01-02 00:00:00 2026-05-30 00:00:00 31.17

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001QTKG'
        ORDER BY date_mesure

BSS001QTKG : 12767 lignes chargées
BSS001QTKG 1990-08-09 00:00:00 2026-05-30 00:00:00 118.59

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001QSMT'
        ORDER BY date_mesure

BSS001QSMT : 8606 lignes chargées
BSS001QSMT 2002-07-23 00:00:00 2026-05-30 00:00:00 108.47

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001QHYH'
        ORDER BY date_mesure

BSS001QHYH : 14532 lignes chargées
BSS001QHYH 1985-06-24 00:00:00 2026-05-30 00:00:00 12.22

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001QHPU'
        ORDER BY date_mesure

BSS001QHPU : 12002 lignes chargées
BSS001QHPU 1993-05-12 00:00:00 2026-05-30 00:00:00 3.72

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001RQQE'
        ORDER BY date_mesure

BSS001RQQE : 11477 lignes chargées
BSS001RQQE 1993-07-21 00:00:00 2026-05-30 00:00:00 77.98

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001SHNE'
        ORDER BY date_mesure

BSS001SHNE : 12121 lignes chargées
BSS001SHNE 1992-07-23 00:00:00 2026-05-30 00:00:00 6.3

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001VAJT'
        ORDER BY date_mesure

BSS001VAJT : 12312 lignes chargées
BSS001VAJT 1991-12-30 00:00:00 2026-05-30 00:00:00 29.34

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001UCZQ'
        ORDER BY date_mesure

BSS001UCZQ : 11647 lignes chargées
BSS001UCZQ 1993-04-09 00:00:00 2026-05-30 00:00:00 143.39

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001XBKZ'
        ORDER BY date_mesure

BSS001XBKZ : 6220 lignes chargées
BSS001XBKZ 2002-01-17 00:00:00 2026-05-29 00:00:00 78.46

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS001WVPW'
        ORDER BY date_mesure

BSS001WVPW : 6887 lignes chargées
BSS001WVPW 2007-06-29 00:00:00 2026-05-30 00:00:00 28.85

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS002AFGV'
        ORDER BY date_mesure

BSS002AFGV : 6340 lignes chargées
BSS002AFGV 2006-04-26 00:00:00 2026-05-29 00:00:00 11.55

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS002AXYY'
        ORDER BY date_mesure

BSS002AXYY : 10044 lignes chargées
BSS002AXYY 1976-01-01 00:00:00 2026-05-29 00:00:00 55.19

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS002CAAM'
        ORDER BY date_mesure

BSS002CAAM : 6510 lignes chargées
BSS002CAAM 2007-12-19 00:00:00 2026-05-30 00:00:00 113.19

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS002BGAF'
        ORDER BY date_mesure

BSS002BGAF : 6456 lignes chargées
BSS002BGAF 2007-12-05 00:00:00 2026-05-29 00:00:00 59.91

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        SELECT date_mesure, niveau_nappe_eau
        FROM `hydro-sense-498112.piezometry.chroniques_piezo`
        WHERE bss_id = 'BSS002EDYK'
        ORDER BY date_mesure

BSS002EDYK : 12108 lignes chargées
BSS002EDYK 1992-10-23 00:00:00 2026-05-18 00:00:00 26.83
CPU times: user 3.17 s, sys: 59.2 ms, total: 3.23 s
Wall time: 27.3 s

  date_mesure  niveau_nappe_eau
0  1992-10-23             28.14
1  1992-10-24             28.18
2  1992-10-25             28.30
3  1992-10-26             28.38
4  1992-10-27             28.38

In [8]:
df

             niveau_nappe_eau
date_mesure
1959-01-01              90.79
1996-04-18              91.28
1996-04-19              91.28
1996-04-20              91.28
1996-04-21              91.27
...                       ...
2026-05-26              91.26
2026-05-27              91.25
2026-05-28              91.24
2026-05-29              91.23
2026-05-30              91.22

[10755 rows x 1 columns]

### Injection du Preprocess.

In [ ]:
from hydrosense.database.bigquery import load_piezo_bq
from hydrosense.preprocess.cleaning import clean_piezo

### Test Upload

In [7]:
# 3 test uploadinf

df_test = pd.read_csv(f'../raw_data/piezo_BSS001BLTP.csv', sep = ';')
df_test.head()

  date_mesure  niveau_nappe_eau  profondeur_nappe
0  1994-04-22             44.19             44.19
1  1994-04-23             44.29             44.29
2  1994-04-24             44.26             44.26
3  1994-04-25             44.22             44.22
4  1994-04-26             44.19             44.19

In [8]:
TABLE = "piezo_upload_test"

table = f"{GCP_PROJECT_ID}.{DATASET}.{TABLE}"

client = bigquery.Client()

write_mode = "WRITE_TRUNCATE" # or "WRITE_APPEND"
job_config = bigquery.LoadJobConfig(write_disposition=write_mode)

job = client.load_table_from_dataframe(df_test, table, job_config=job_config)
result = job.result()

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

In [18]:
dir(result)
result.total_rows

100

In [10]:
TABLE = "piezo_upload_test"

query = f"""
    SELECT *
    FROM {GCP_PROJECT_ID}.{DATASET}.{TABLE}
    LIMIT 100
"""

query_job = client.query(query)
result = query_job.result()
df = result.to_dataframe()
df.head()

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

  date_mesure  niveau_nappe_eau  profondeur_nappe
0  2005-10-13             36.88             36.88
1  2005-10-12             36.90             36.90
2  2005-10-09             36.92             36.92
3  2005-10-11             36.92             36.92
4  2005-10-10             36.94             36.94

## 4. Upload de catalogue piezo

Catalogue des métadonnées des stations du réseau Ades

In [11]:
from hydrosense.database.ades import GestionnairePiezometrie
from hydrosense.database.entite import Entite

In [12]:
extracteur = Entite()
extracteur.total_stations(nb_mesures_piezo_min = 360)

Nombre total de stations trouvées : 5025

In [13]:
liste_piezo = extracteur.rechercher_stations(nb_mesures_piezo_min = 360, taille_max= 20_000)
df = extracteur.generer_df()

Recherche des stations avec les paramètres : {'format': 'json', 'size': 20000, 'nb_mesures_piezo_min': 360}...
-> 5025 stations trouvées !
df en entrée :  Index(['code_bss', 'urn_bss', 'date_debut_mesure', 'date_fin_mesure',
       'code_commune_insee', 'nom_commune', 'x', 'y', 'codes_bdlisa',
       'urns_bdlisa', 'geometry', 'bss_id', 'altitude_station',
       'nb_mesures_piezo', 'code_departement', 'nom_departement', 'libelle_pe',
       'profondeur_investigation', 'codes_masse_eau_edl', 'noms_masse_eau_edl',
       'urns_masse_eau_edl', 'date_maj'],
      dtype='object')

/home/charourou/projects/Projet_Hydrosense/hydrosense/database/entite.py:133: FutureWarning: Parsing 'CEST' as tzlocal (dependent on system timezone) is deprecated and will raise in a future version. Pass the 'tz' keyword or call tz_localize after construction instead
  return pd.to_datetime(str(valeur), utc=True)
/home/charourou/projects/Projet_Hydrosense/hydrosense/database/entite.py:133: FutureWarning: Parsing 'CET' as tzlocal (dependent on system timezone) is deprecated and will raise in a future version. Pass the 'tz' keyword or call tz_localize after construction instead
  return pd.to_datetime(str(valeur), utc=True)

df en sortie :  Index(['altitude_station', 'bss_id', 'code_bss', 'code_commune_insee',
       'code_departement', 'codes_bdlisa', 'codes_masse_eau_edl',
       'date_debut_mesure', 'date_fin_mesure', 'date_maj', 'geometry',
       'libelle_pe', 'nb_mesures_piezo', 'nom_commune', 'nom_departement',
       'noms_masse_eau_edl', 'profondeur_investigation', 'urn_bss',
       'urns_bdlisa', 'urns_masse_eau_edl', 'x', 'y'],
      dtype='object')
-> Catalogue structuré en DataFrame (5025 lignes, 22 colonnes).

In [10]:
df.head()

,altitude_station,bss_id,code_bss,code_commune_insee,code_departement,codes_bdlisa,codes_masse_eau_edl,date_debut_mesure,date_fin_mesure,date_maj,...,nb_mesures_piezo,nom_commune,nom_departement,noms_masse_eau_edl,profondeur_investigation,urn_bss,urns_bdlisa,urns_masse_eau_edl,x,y
0,61.29,BSS002PJXA,12288X0089/PIEZO.,97416,974,974AT01,LG106,1996-11-13 00:00:00+00:00,2026-05-26 00:00:00+00:00,NaT,...,8740,Saint-Pierre,La Réunion,Formations volcaniques et volcano-sédimentaire...,200.00,http://services.ades.eaufrance.fr/pointeau/122...,http://reseau.eaufrance.fr/geotraitements/bdli...,[http://www.sandre.eaufrance.fr/geo/MasseDEauS...,55.459616,-21.317968
1,179.2,BSS000YWFY,03423X0020/100,68113,68,221AA17,CG101,1954-11-08 00:00:00+00:00,1988-12-27 00:00:00+00:00,NaT,...,1582,Guémar,Haut-Rhin,"Nappe d’Alsace, Pliocène de Haguenau et Oligocène",11.00,http://services.ades.eaufrance.fr/pointeau/034...,http://reseau.eaufrance.fr/geotraitements/bdli...,[http://www.sandre.eaufrance.fr/geo/MasseDEauS...,7.396859,48.190279
2,174.0,BSS000YWHH,03423X0056/100,68113,68,221AA15,CG101,1954-11-08 00:00:00+00:00,2026-05-23 00:00:00+00:00,NaT,...,5158,Guémar,Haut-Rhin,"Nappe d’Alsace, Pliocène de Haguenau et Oligocène",10.70,http://services.ades.eaufrance.fr/pointeau/034...,http://reseau.eaufrance.fr/geotraitements/bdli...,[http://www.sandre.eaufrance.fr/geo/MasseDEauS...,7.396716,48.190195
3,179.7,BSS000YZZR,03428X0021/200,67281,67,221AA17,CG101,1954-04-24 00:00:00+00:00,1974-04-02 00:00:00+00:00,NaT,...,994,Marckolsheim,Bas-Rhin,"Nappe d’Alsace, Pliocène de Haguenau et Oligocène",3.60,http://services.ades.eaufrance.fr/pointeau/034...,http://reseau.eaufrance.fr/geotraitements/bdli...,[http://www.sandre.eaufrance.fr/geo/MasseDEauS...,7.542952,48.134318
4,-999.0,BSS001TULG,07011X0117/RN00,01039,01,712AH37,None,2014-07-01 00:00:00+00:00,2016-09-02 00:00:00+00:00,NaT,...,795,Béon,Ain,None,1.63,http://services.ades.eaufrance.fr/pointeau/070...,http://reseau.eaufrance.fr/geotraitements/bdli...,[],5.757082,45.847673

In [11]:
df['date_fin_mesure'].sort_values()

169    1964-06-04 00:00:00+00:00
1820   1965-09-23 00:00:00+00:00
2340   1967-01-31 00:00:00+00:00
2486   1967-01-31 00:00:00+00:00
1685   1967-06-27 00:00:00+00:00
                  ...
234    2026-05-29 00:00:00+00:00
3753   2026-05-29 00:00:00+00:00
3000   2026-05-29 00:00:00+00:00
1341   2026-05-29 00:00:00+00:00
1794   2026-05-30 00:00:00+00:00
Name: date_fin_mesure, Length: 5025, dtype: datetime64[ns, UTC]

Issue with dtype: datetime64[ns, UTC] imported to bigquery -> it becomes a integer !!

In [19]:
TABLE = "cat_piezo_raw"

table = f"{GCP_PROJECT_ID}.{DATASET}.{TABLE}"

client = bigquery.Client()

write_mode = "WRITE_TRUNCATE" # or "WRITE_APPEND"
job_config = bigquery.LoadJobConfig(write_disposition=write_mode)
job = client.load_table_from_dataframe(df, table, job_config=job_config)
result = job.result()

/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(
/home/charourou/.pyenv/versions/Projet_Hydrosense/lib/python3.10/site-packages/google/cloud/bigquery/_pandas_helpers.py:553: UserWarning: Could not determine the type of columns: geometry
  warnings.warn(msg)

In [ ]:
result.output_rows

LoadJob<project=hydro-sense-498112, location=US, id=22f15051-493b-4dfd-8e77-fcc9e7ced33b>